version: '2'

services:
  api:
    image: registry.spin.nersc.gov/scott/apm:0.2
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
