version: '2'

services:
    kv:
        image: couchdb:2.2.0
        restart: always
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        ports:
          - 50003:5984
        volumes:
         - kv.dev-couchdb-pi-jgi-01:/opt/couchdb/data
         - kv.dev-couchdb-pi-jgi-01:/opt/couchdb/etc
         - kv.dev-couchdb-pi-jgi-01:/opt/couchdb/etc/local.d
volumes:
    kv.dev-couchdb-pi-jgi-01:
        driver: rancher-nfs
        external: true
