###################### Filebeat Configuration Example #########################

# For more available modules and options, please see the filebeat.reference.yml sample
# configuration file.

#=========================== Filebeat inputs =============================

filebeat.inputs:
  - type: log
    paths:
      - /var/log/app/new/*.log
    fields:
      type: syslog
processors:
  - add_fields:
      fields:
        environment: 'development'
        group: 'pi'
        team: 'pps'
output.logstash:
  hosts: ["metrix.jgi.doe.gov:5044"]
