version: '2'

services:
    kv:
        image: couchdb:2.2.0
        restart: always
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        ports:
          - 50002:5984
        volumes:
          - kv.jgi-pi-couchdb-int:/opt/couchdb/data
          - kv.jgi-pi-couchdb-int:/opt/couchdb/etc/local.d
volumes:
    kv.jgi-pi-couchdb-int:
        driver: rancher-nfs
        external: true
