version: '2'

services:
  kv:
    image: couchdb:2.3.1
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    ports:
      - 5984:5984
    volumes:
      - kv.dev-couchdb-pi-jgi-02.data:/opt/couchdb/data
      - kv.dev-couchdb-pi-jgi-02.local:/opt/couchdb/etc/local.d
      - kv.dev-couchdb-pi-jgi-02.log:/opt/couchdb/var/log
  lb:
    image: registry.spin.nersc.gov/scott/filebeat:6.6.2-0.17
    environment:
      - LOGSTASH_HOST=zuul-dev.jgi.doe.gov
      - LOGSTASH_PORT=5044
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/app/new
      - lb.dev-couchdb-pi-jgi-02.old:/var/log/app/old
      - lb.dev-couchdb-pi-jgi-02.rot:/usr/share/logrotate
  api:
    image: registry.spin.nersc.gov/scott/logrotate:0.16
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/app/new
      - lb.dev-couchdb-pi-jgi-02.old:/var/log/app/old
      - lb.dev-couchdb-pi-jgi-02.rot:/usr/share/logrotate
    labels:
      # prevent running stale (cached) image on restart or upgrade
      io.rancher.container.pull_image: always
      # run every minute (for testing)
      cron.schedule: 0 * * * * *
      # override default behavior to restart container after backup process completes
      io.rancher.container.start_once: 'true'
volumes:
  kv.dev-couchdb-pi-jgi-02.data:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.local:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.log:
    driver: rancher-nfs
    external: true
  lb.dev-couchdb-pi-jgi-02.old:
    driver: rancher-nfs
    external: true
  lb.dev-couchdb-pi-jgi-02.rot:
      driver: rancher-nfs
      external: true

