version: '2'

services:
  kv:
    image: couchdb:2.3.1
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    ports:
      - 5984:5984
    volumes:
      - kv.dev-couchdb-pi-jgi-02.data:/opt/couchdb/data
      - kv.dev-couchdb-pi-jgi-02.local:/opt/couchdb/etc/local.d
      - kv.dev-couchdb-pi-jgi-02.log:/opt/couchdb/var/log
  lb:
    image: registry.spin.nersc.gov/scott/filebeat:6.6.1-0.6
    environment:
      - LOGSTASH_HOST=zuul-dev.jgi.doe.gov
      - LOGSTASH_PORT=5044
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - lb.dev-couchdb-pi-jgi-02.conf:/usr/share/filebeat
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/filebeat/logs
  api:
    image: registry.spin.nersc.gov/scott/logrotate:0.6
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - api.dev-couchdb-pi-jgi-02.conf:/usr/share/logrotate
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/filebeat/logs
    labels:
      # prevent running stale (cached) image on restart or upgrade
      io.rancher.container.pull_image: always
      # run every 15 minutes
      cron.schedule: 0,1,2,3,4,5,6,15,30,45 * * * *
      # override default behavior to restart container after backup process completes
      io.rancher.container.start_once: 'true'
volumes:
  kv.dev-couchdb-pi-jgi-02.data:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.local:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.log:
    driver: rancher-nfs
    external: true
  lb.dev-couchdb-pi-jgi-02.conf:
    driver: rancher-nfs
    external: true
  api.dev-couchdb-pi-jgi-02.conf:
      driver: rancher-nfs
      external: true
