version: '2'

services:
  kv:
    image: couchdb:2.3.1
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    ports:
      - 5984:5984
    volumes:
      - kv.dev-couchdb-pi-jgi-02.data:/opt/couchdb/data
      - kv.dev-couchdb-pi-jgi-02.etc:/opt/couchdb/etc
      - kv.dev-couchdb-pi-jgi-02.log:/opt/couchdb/var/log
  beat:
    image: registry.spin.nersc.gov/scott/filebeat:6.6.2-0.5
    environment:
      - LOGSTASH_HOST=zuul-dev.jgi.doe.gov
      - LOGSTASH_PORT=5044
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - beat.dev-couchdb-pi-jgi-02.conf:/usr/share/filebeat
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/filebeat/logs
  rotate:
    image: registry.spin.nersc.gov/scott/logrotate:0.5
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - rotate.dev-couchdb-pi-jgi-02.conf:/usr/share/logrotate
      - kv.dev-couchdb-pi-jgi-02.log:/var/log/filebeat/logs
    labels:
      # prevent running stale (cached) image on restart or upgrade
      io.rancher.container.pull_image: always
      # run every 15 minutes
      cron.schedule: 0,15,30,45 * * * *
      # override default behavior to restart container after backup process completes
      io.rancher.container.start_once: 'true'
volumes:
  kv.dev-couchdb-pi-jgi-02.data:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.etc:
    driver: rancher-nfs
    external: true
  kv.dev-couchdb-pi-jgi-02.log:
    driver: rancher-nfs
    external: true
