FROM docker.elastic.co/beats/filebeat:6.6.1
USER root
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml && \
  mkdir -p /usr/share/filebeat/logs/old && \
  mkdir /etc/supervisord.d && \
  yum -y update && \
  yum install -y epel-release && \
  yum -y install logrotate  && \
  yum -y install supervisor cronie yum-cron && \
  yum clean all
COPY supervisord.conf /etc/supervisord.conf
COPY crond.ini /etc/supervisord.d/crond.ini
RUN chmod 664 /etc/supervisord.conf /etc/supervisord.d/*.ini && \
  mkdir -p /var/lock/subsys && \
  touch /var/lock/subsys/yum-cron && \
  sed -i 's/apply_updates = no/apply_updates = yes/' /etc/yum/yum-cron.conf && \
  sed -i 's/apply_updates = no/apply_updates = yes/' /etc/yum/yum-cron-hourly.conf
CMD ["/usr/bin/supervisord"]
