version: '2'

services:
    kv:
        image: couchdb:2.2.0
        restart: always
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        ports:
          - 50003:5984
#        volumes:
#          - kv.jgi-pi-couchdb-dev:/opt/couchdb
#volumes:
#    kv.jgi-pi-couchdb-dev:
#        driver: rancher-nfs
#        external: true
